name: AI GitHub Commenter

on:
  schedule:
    - cron: '0 10 * * *'  # Runs daily at 10:00 UTC
  workflow_dispatch:       # Allows manual run

jobs:
  comment-on-issues:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run AI commenter
      run: python scripts/main.py
